development:
  adapter: postgresql
  encoding: unicode
  database: stoop_application_development
  pool: 5
  username: tanayjalan
  password:
  host: localhost

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: stoop_sale_test
#   pool: 5
#   username: stoop_sale
#   password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: stoop_sale_production
#   pool: 5
#   username: stoop_sale
#   password:


